fix: 깃액션 수정

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -97,7 +97,7 @@
               for i in {1..15}; do
               echo "($i/15) curl 시도 중..."
               
-              RESPONSE=$(curl -s -w "\nHTTP_CODE:%{http_code}" http://localhost:8080/actuator/health || echo "FAILED")
+              RESPONSE=$(curl -s -w "\nHTTP_CODE:%{http_code}" http://localhost:8080/health || echo "FAILED")
               
               echo "Raw RESPONSE:"
               echo "$RESPONSE"
